version: '3.5'

services:
  edge-ui:
    container_name: edge-ui
    image: edgemm:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:4200/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
    expose:
      - 4200
    # volumes:
    #   - '.:/usr/src/app'
    #   - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
    networks:
      - edge-network